---
title: "Phyloseq creation"
output:
  html_document:
    theme: united
    highlight: breezedark
    toc: yes
    toc_float: true
    df_print: paged
---

# Create phyloseq object for Pseudomonas amplicon

```{r eval=FALSE}
library(phyloseq)
library(dplyr)

# read meta data
setwd(HOME_LOCAL)
meta <- data.table::fread("02_Labels.txt", stringsAsFactors = F, colClasses = c(rep("character",15),rep("integer",2)) )
barcodes <- data.table::fread("02_Barcodes.txt")

# combine meta and borcode info
barcodes_Fwd <- barcodes[barcodes$Orientation=="Frw",c(1:2)]
colnames(barcodes_Fwd) <- c("Barcode_Nr_Fwd","Barcode_id_Fwd")

barcodes_Rev <- barcodes[barcodes$Orientation=="Rev",c(1:2)]
colnames(barcodes_Rev) <- c("Barcode_Nr_Rev","Barcode_id_Rev")

meta <- left_join(meta, barcodes_Fwd, by=c("Barcode_Nr_Fwd"="Barcode_Nr_Fwd"))
meta <- left_join(meta, barcodes_Rev, by=c("Barcode_Nr_Rev"="Barcode_Nr_Rev"))


for(amp in c("LSP36_LSP46")){
  
  # create file name column to merge later
  meta$file_run1 <- paste("m64141e_210513_212412.reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")
  meta$file_run2 <- paste("m64141e_221218_125051.hifi_reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, "_filtered.fastq", sep = "")

  meta1 <- data.frame(meta, row.names = meta$file_run1)
  meta1 <- meta1[meta1$Sample_type=="L",]
  meta2 <- data.frame(meta, row.names = meta$file_run2)
  meta2 <- meta2[meta2$Sample_type=="L",]
  meta_all <- rbind(meta1, meta2)
  meta_all <- meta_all %>% mutate_if(is.character, as.factor)
  
  # add run number
  meta_all$Sample_id <- rownames(meta_all)
  meta_all <- meta_all %>%
  mutate(Run_nr = ifelse(startsWith(Sample_id, "m64141e_210513_212412.reads.split."), 1,
                         ifelse(startsWith(Sample_id, "m64141e_221218_125051.hifi_reads.split."), 2, NA)))
  meta_all <- meta_all %>% mutate_if(is.numeric, as.factor)

  # read seqtable (sequence counts per sample)
  setwd(paste(HOME_LOCAL, "Dataset2_dada2_workflow", sep = "/"))
  asv <- data.table::fread(paste(amp,"asv_table_pool.txt", sep = "_"))
  row.names(asv) <- as.character(asv$V1)
  asv <- asv %>% select(-V1)

  # read fasta to connect sequences with asv names
  asv_names <- read.table(paste(amp,"asv.fa", sep = "_"), header = F)
  asv_names <- data.frame(header = sub(asv_names[seq(1, nrow(asv_names)-1, by = 2),1], pattern = ">", replacement = ""),
                         sequence = asv_names[seq(2, nrow(asv_names), by = 2),1] )

  # rename seqtable sequences to asv names for more readability later
  col_headers <- data.frame(col_header = colnames(asv))
  col_headers <- left_join(col_headers, asv_names, by = c("col_header" = "sequence"))
  colnames(asv) <- as.character(col_headers$header)

  # format seqtable as matrix with samples in columns, sequences in rows 
  asv <- as.matrix(asv, rownames = row.names(asv))
  asv_t <- t(asv)
  
  # read Pseudomonas taxonomy annotation
  setwd(paste(HOME_LOCAL,"Pseudomonas_blast", sep = "/"))
  taxmat <- read.table(file = paste(amp, "_blast_summary_2.txt", sep = ""), header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  row.names(taxmat) <- taxmat$qseqid
  taxmat <- taxmat[,-c(1)]
  taxmat <- as.matrix(taxmat)
  
  # read in tree
  #setwd(paste(HOME_LOCAL,"PS_trees", sep = "/"))
  #tree <- phytools::read.newick(paste(amp, ".marker001.",amp, "_asv.fa.aln.FastTree.tree", sep = "")) # FastTree
  
  # make phyloseq object
  otu <- otu_table(asv_t, taxa_are_rows = T)
  samples <- sample_data(meta_all)
  taxmat <- tax_table(taxmat)
  
  physeq <- phyloseq(otu, samples, taxmat, tree)
  saveRDS(physeq, file = paste(HOME_LOCAL, "physeq_", amp, ".rds", sep = ""))
   
  # merge species
  tax_table(physeq) <- tax_table(physeq)[,c(16, 1:15, 17:ncol(data.frame(physeq@tax_table)))]
  physeq2 <- tax_glom(physeq = physeq, taxrank = "Species", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_species_merged.rds", sep = ""))
  
  # normalize counts among samples
  # don't do this now, as this is done by SPIEC-EASI afterwards
  # physeq <- transform_sample_counts(physeq, function (x) x / sum(x))
  
  # get tot abundance
  tot <- sum(physeq@otu_table, na.rm = TRUE)
  
  gdata::mv(from = "physeq", to = paste("physeq", amp, sep = "_"))
  gdata::mv(from = "tot", to = paste("tot", amp, sep = "_")) 
  
}

```


# Create phyloseq object for 16S amplicon


```{r eval=FALSE}

# read meta data
setwd(HOME_LOCAL)
meta <- data.table::fread("02_Labels.txt", stringsAsFactors = F, colClasses = c(rep("character",15),rep("integer",2)) )
barcodes <- data.table::fread("02_Barcodes.txt")

# combine meta and borcode info
barcodes_Fwd <- barcodes[barcodes$Orientation=="Frw",c(1:2)]
colnames(barcodes_Fwd) <- c("Barcode_Nr_Fwd","Barcode_id_Fwd")

barcodes_Rev <- barcodes[barcodes$Orientation=="Rev",c(1:2)]
colnames(barcodes_Rev) <- c("Barcode_Nr_Rev","Barcode_id_Rev")

meta <- left_join(meta, barcodes_Fwd, by=c("Barcode_Nr_Fwd"="Barcode_Nr_Fwd"))
meta <- left_join(meta, barcodes_Rev, by=c("Barcode_Nr_Rev"="Barcode_Nr_Rev"))


for(amp in c("LSP48_LSP49")){

  # create file name column to merge later
  meta$file_run1 <- paste("m64141e_210513_212412.reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")
  meta$file_run2 <- paste("m64141e_221218_125051.hifi_reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")

  meta1 <- data.frame(meta, row.names = meta$file_run1)
  meta1 <- meta1[meta1$Sample_type=="L",]
  meta2 <- data.frame(meta, row.names = meta$file_run2)
  meta_all <- rbind(meta1, meta2)
  meta_all <- meta_all %>% mutate_if(is.character, as.factor)

  # read seqtable (sequence counts per sample)
  asv <- data.table::fread(paste(amp,"asv_table_pool.txt", sep = "_"))
  row.names(asv) <- as.character(asv$V1)
  asv <- asv %>% select(-V1)

  # read fasta to connect sequences with asv names
  asv_names <- read.table(paste(amp,"asv.fa", sep = "_"), header = F)
  asv_names <- data.frame(header = sub(asv_names[seq(1, nrow(asv_names)-1, by = 2),1], pattern = ">", replacement = ""),
                         sequence = asv_names[seq(2, nrow(asv_names), by = 2),1] )

  # rename seqtable sequences to asv names for more readability later
  col_headers <- data.frame(col_header = colnames(asv))
  col_headers <- left_join(col_headers, asv_names, by = c("col_header" = "sequence"))
  colnames(asv) <- as.character(col_headers$header)

  # format seqtable as matrix with samples in columns, sequences in rows 
  asv <- as.matrix(asv, rownames = row.names(asv))
  asv_t <- t(asv)
  
  # read taxonomy format
  taxmat <- read.table(paste(HOME_LOCAL,"02_LSP48_LSP49_silva_species_assignment_v138.txt", sep = "/"), 
                       header = TRUE, stringsAsFactors = F, sep = "\t", row.names = NULL)
  row.names(taxmat) <- taxmat$header
  taxmat <- taxmat[,-c(1:3)]
  taxmat <- as.matrix(taxmat)
  
  # make phyloseq object
  otu <- otu_table(asv_t, taxa_are_rows = T)
  samples <- sample_data(meta_all)
  taxmat <- tax_table(taxmat)
  
  physeq <- phyloseq(otu, samples, taxmat)
  
  # filter out chloroplast
  physeq_sub <-subset_taxa(physeq, Order != "Chloroplast") 
  saveRDS(physeq_sub, file = paste(HOME_LOCAL, "physeq_", amp, ".rds", sep = ""))
  
  # merge species
  physeq2 <- physeq_sub
  tax_table(physeq2) <- tax_table(physeq2)[,c(7, 1:6)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Species", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_species_merged.rds", sep = ""))
  
  # merge genus
  physeq2 <- physeq_sub
  tax_table(physeq2) <- tax_table(physeq2)[,c(6, 1:5,7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Genus", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_genus_merged.rds", sep = ""))
  
  # merge family
  physeq2 <- physeq_sub
  tax_table(physeq2) <- tax_table(physeq2)[,c(5, 1:4,6:7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Family", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_family_merged.rds", sep = ""))
  
  # merge order
  physeq2 <- physeq_sub
  tax_table(physeq2) <- tax_table(physeq2)[,c(4, 1:3,5:7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Order", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_order_merged.rds", sep = ""))
   
}

```



# Create phyloseq object for Zymoseptoria tritici amplicon

```{r eval=FALSE}
library(phyloseq)
library(dplyr)

# read meta data
setwd(HOME_LOCAL)
meta <- data.table::fread("02_Labels.txt", stringsAsFactors = F, colClasses = c(rep("character",15),rep("integer",2)) )
barcodes <- data.table::fread("02_Barcodes.txt")

# combine meta and borcode info
barcodes_Fwd <- barcodes[barcodes$Orientation=="Frw",c(1:2)]
colnames(barcodes_Fwd) <- c("Barcode_Nr_Fwd","Barcode_id_Fwd")

barcodes_Rev <- barcodes[barcodes$Orientation=="Rev",c(1:2)]
colnames(barcodes_Rev) <- c("Barcode_Nr_Rev","Barcode_id_Rev")

meta <- left_join(meta, barcodes_Fwd, by=c("Barcode_Nr_Fwd"="Barcode_Nr_Fwd"))
meta <- left_join(meta, barcodes_Rev, by=c("Barcode_Nr_Rev"="Barcode_Nr_Rev"))


for(amp in c("LSP15_LSP16")){
  
  # create file name column to merge later
  meta$file_run1 <- paste("m64141e_210513_212412.reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")
  meta$file_run2 <- paste("m64141e_221218_125051.hifi_reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, "_filtered.fastq", sep = "")

  meta1 <- data.frame(meta, row.names = meta$file_run1)
  meta1 <- meta1[meta1$Sample_type=="L",]
  meta2 <- data.frame(meta, row.names = meta$file_run2)
  meta2 <- meta2[meta2$Sample_type=="L",]
  meta_all <- rbind(meta1, meta2)
  meta_all <- meta_all %>% mutate_if(is.character, as.factor)
  
  # add run number
  meta_all$Sample_id <- rownames(meta_all)
  meta_all <- meta_all %>%
  mutate(Run_nr = ifelse(startsWith(Sample_id, "m64141e_210513_212412.reads.split."), 1,
                         ifelse(startsWith(Sample_id, "m64141e_221218_125051.hifi_reads.split."), 2, NA)))
  meta_all <- meta_all %>% mutate_if(is.numeric, as.factor)

  # read seqtable (sequence counts per sample)
  setwd(paste(HOME_LOCAL, "Dataset2_dada2_workflow", sep = "/"))
  asv <- data.table::fread(paste(amp,"asv_table_pool.txt", sep = "_"))
  row.names(asv) <- as.character(asv$V1)
  asv <- asv %>% select(-V1)

  # read fasta to connect sequences with asv names
  asv_names <- read.table(paste(amp,"asv.fa", sep = "_"), header = F)
  asv_names <- data.frame(header = sub(asv_names[seq(1, nrow(asv_names)-1, by = 2),1], pattern = ">", replacement = ""),
                         sequence = asv_names[seq(2, nrow(asv_names), by = 2),1] )

  # rename seqtable sequences to asv names for more readability later
  col_headers <- data.frame(col_header = colnames(asv))
  col_headers <- left_join(col_headers, asv_names, by = c("col_header" = "sequence"))
  colnames(asv) <- as.character(col_headers$header)

  # format seqtable as matrix with samples in columns, sequences in rows 
  asv <- as.matrix(asv, rownames = row.names(asv))
  asv_t <- t(asv)
  
  # read in tree
  #setwd(paste(HOME_LOCAL,"Zymo_trees", sep = "/"))
  #tree <- phytools::read.newick(paste(amp, ".marker001.",amp, "_asv.fa.aln.FastTree.tree", sep = "")) # FastTree
  
  # make phyloseq object
  otu <- otu_table(asv_t, taxa_are_rows = T)
  samples <- sample_data(meta_all)
 
  physeq <- phyloseq(otu, samples, tree)
  saveRDS(physeq, file = paste(HOME_LOCAL, "physeq_", amp, ".rds", sep = ""))
  
  # normalize counts among samples
  # don't do this now, as this is done by SPIEC-EASI afterwards
  # physeq <- transform_sample_counts(physeq, function (x) x / sum(x))
  
  # subset to get the most abundant ASVs only
  physeq2 <- prune_taxa(x = physeq, taxa = names(taxa_sums(physeq)[1:100]))
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_top100.rds", sep = ""))
  
  # get tot abundance
  tot <- sum(physeq@otu_table, na.rm = TRUE)
  
  gdata::mv(from = "physeq", to = paste("physeq", amp, sep = "_"))
  gdata::mv(from = "tot", to = paste("tot", amp, sep = "_")) 

}

```


# Create phyloseq object for ITS amplicon

```{r}
library(phyloseq)
library(dplyr)

# read meta data
setwd(HOME_LOCAL)
meta <- data.table::fread("02_Labels.txt", stringsAsFactors = F, colClasses = c(rep("character",15),rep("integer",2)) )
barcodes <- data.table::fread("02_Barcodes.txt")

# combine meta and borcode info
barcodes_Fwd <- barcodes[barcodes$Orientation=="Frw",c(1:2)]
colnames(barcodes_Fwd) <- c("Barcode_Nr_Fwd","Barcode_id_Fwd")

barcodes_Rev <- barcodes[barcodes$Orientation=="Rev",c(1:2)]
colnames(barcodes_Rev) <- c("Barcode_Nr_Rev","Barcode_id_Rev")

meta <- left_join(meta, barcodes_Fwd, by=c("Barcode_Nr_Fwd"="Barcode_Nr_Fwd"))
meta <- left_join(meta, barcodes_Rev, by=c("Barcode_Nr_Rev"="Barcode_Nr_Rev"))


for(amp in c("LSP08_LSP10")){

  # create file name column to merge later
  meta$file_run1 <- paste("m64141e_210513_212412.reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")
  meta$file_run2 <- paste("m64141e_221218_125051.hifi_reads.split.", meta$Barcode_id_Fwd, "--", meta$Barcode_id_Rev, ".", amp, ".fastq", sep = "")

  meta1 <- data.frame(meta, row.names = meta$file_run1)
  meta1 <- meta1[meta1$Sample_type=="L",]
  meta2 <- data.frame(meta, row.names = meta$file_run2)
  meta_all <- rbind(meta1, meta2)
  meta_all <- meta_all %>% mutate_if(is.character, as.factor)

  # read seqtable (sequence counts per sample)
  asv <- data.table::fread(paste(amp,"asv_table_pool.txt", sep = "_"))
  row.names(asv) <- as.character(asv$V1)
  asv <- asv %>% select(-V1)

  # read fasta to connect sequences with asv names
  asv_names <- read.table(paste(amp,"asv.fa", sep = "_"), header = F)
  asv_names <- data.frame(header = sub(asv_names[seq(1, nrow(asv_names)-1, by = 2),1], pattern = ">", replacement = ""),
                         sequence = asv_names[seq(2, nrow(asv_names), by = 2),1] )

  # rename seqtable sequences to asv names for more readability later
  col_headers <- data.frame(col_header = colnames(asv))
  col_headers <- left_join(col_headers, asv_names, by = c("col_header" = "sequence"))
  colnames(asv) <- as.character(col_headers$header)

  # format seqtable as matrix with samples in columns, sequences in rows 
  asv <- as.matrix(asv, rownames = row.names(asv))
  asv_t <- t(asv)
  
  # read taxonomy format
  taxmat <- read.table(paste(HOME_LOCAL,"02_LSP08_LSP10_sub_bed_unite_species_assignment_dynamic_29.11.2022.txt", 
                             sep = "/"), header = TRUE, stringsAsFactors = F, sep = "\t", row.names = NULL)
  row.names(taxmat) <- taxmat$ASV
  taxmat <- taxmat[,-c(1:2)]
  taxmat <- as.matrix(taxmat)
  
  
  # make phyloseq object
  otu <- otu_table(asv_t, taxa_are_rows = T)
  samples <- sample_data(meta_all)
  taxmat <- tax_table(taxmat)
  
  physeq <- phyloseq(otu, samples, taxmat)
  saveRDS(physeq, file = paste(HOME_LOCAL, "physeq_", amp, ".rds", sep = ""))
  
  # merge species
  physeq2 <- physeq
  tax_table(physeq2) <- tax_table(physeq2)[,c(7, 1:6)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Species", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_species_merged.rds", sep = ""))
  
  # merge genus
  physeq2 <- physeq
  tax_table(physeq2) <- tax_table(physeq2)[,c(6, 1:5,7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Genus", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_genus_merged.rds", sep = ""))
  
  # merge family
  physeq2 <- physeq
  tax_table(physeq2) <- tax_table(physeq2)[,c(5, 1:4,6:7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Family", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_family_merged.rds", sep = ""))
  
  # merge order
  physeq2 <- physeq
  tax_table(physeq2) <- tax_table(physeq2)[,c(4, 1:3,5:7)]
  physeq2 <- tax_glom(physeq = physeq2, taxrank = "Order", NArm = FALSE)
  saveRDS(physeq2, file = paste(HOME_LOCAL, "physeq_", amp, "_order_merged.rds", sep = ""))
   
}
```

